---
general:
  buildTool: "mta"
service:
  buildToolVersion: "MBTJ21N22"
  stages:
    Acceptance:
      cfCredentialsId: "btpamin"
stages:
  Build:
    mavenExecuteStaticCodeChecks: false
    npmExecuteLint: false
  Acceptance:
    cfApiEndpoint: "https://api.cf.us10-001.hana.ondemand.com"
    cfOrg: "c8bb26catrial"
    cfSpace: "dev"
    deployType: "standard"
    cloudFoundryDeploy: true
    npmExecuteEndToEndTests: false
  Malware Scan:
    malwareExecuteScan: true
  Release:
    tmsExport: false
    tmsUpload: true
    cloudFoundryDeploy: false
  Additional Unit Tests:
    npmExecuteScripts: false
  Compliance:
    sonarExecuteScan: true
steps:
  cloudFoundryDeploy:
    mtaDeployParameters: "-f --version-rule ALL"
  tmsUpload:
    nodeName: "dev"
    credentialsId: "cts-sk"
  sonarExecuteScan:
    mode: "SonarCloud"
    serverUrl: "https://sonarcloud.io"
    organization: "aalmarsafy"
    projectKey: "aalmarsafy_sapui5sample"
    sonarTokenCredentialsId: "sonartoken"
  artifactPrepareVersion:
    versioningType: "cloud_noTag"
